export const mode = state => state.mode
export const articleList = state => state.articleList
export const currentIndex = state => state.currentIndex
export const _id = state => state._id
export const isLogin = state => state.isLogin
export const token = state => state.token
export const curRoute = state => state.curRoute
export const labels = state => state.labels
export const curEdit = state => state.curEdit
export const allAricles = state => state.allAricles
